## Tensorflow 101
### tf.train API exercise

Assume "iris_training.csv" and "iris_test.csv" are in the working directory, and tensorflow is installed.

In [1]:
import tensorflow as tf

In [2]:
from tensorflow.contrib.learn.python.learn.datasets.mnist import DataSet,dense_to_one_hot

In [5]:
import pandas as pd
df = pd.read_csv('iris_training.csv',skiprows=1,header=None)

In [6]:
df.head()

0    1    2    3  4
0  6.4  2.8  5.6  2.2  2
1  5.0  2.3  3.3  1.0  1
2  4.9  2.5  4.5  1.7  2
3  4.9  3.1  1.5  0.1  0
4  5.7  3.8  1.7  0.3  0

In [13]:
ds = DataSet(df.iloc[:,0:4].values,dense_to_one_hot(df.iloc[:,4].values,num_classes=3),reshape=False)

In [14]:
ds.num_examples

120

In [15]:
ds.next_batch(2)

(array([[ 0.02509804,  0.01098039,  0.02196079,  0.00862745],
        [ 0.01960784,  0.00901961,  0.01294118,  0.00392157]], dtype=float32),
 array([[ 0.,  0.,  1.],
        [ 0.,  1.,  0.]]))

In [16]:
ds._index_in_epoch

2

In [18]:
W = tf.Variable(tf.zeros([4,3]),tf.float32)

In [19]:
b = tf.Variable(tf.zeros([1,3]),tf.float32)

In [49]:
x = tf.placeholder(tf.float32,[None,4])
y = tf.placeholder(tf.float32,[None,3])

In [50]:
logits = tf.add(tf.matmul(x,W),b)

In [51]:
sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())

In [52]:
btch_x,btch_y = ds.next_batch(10)
sess.run([logits],feed_dict={x:btch_x})

[array([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]], dtype=float32)]

In [53]:
Z = tf.reduce_sum(tf.exp(logits),axis = 1)

In [54]:
btch_x,btch_y = ds.next_batch(10)
sess.run([Z],feed_dict={x:btch_x})

[array([ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.], dtype=float32)]

In [55]:
eta = tf.exp(logits) 

In [56]:
btch_x,btch_y = ds.next_batch(10)
sess.run([eta,Z],feed_dict={x:btch_x})

[array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=float32),
 array([ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.], dtype=float32)]

In [57]:
p = tf.nn.softmax(logits)

In [58]:
btch_x,btch_y = ds.next_batch(10)
sess.run([p],feed_dict={x:btch_x})

[array([[ 0.33333334,  0.33333334,  0.33333334],
        [ 0.33333334,  0.33333334,  0.33333334],
        [ 0.33333334,  0.33333334,  0.33333334],
        [ 0.33333334,  0.33333334,  0.33333334],
        [ 0.33333334,  0.33333334,  0.33333334],
        [ 0.33333334,  0.33333334,  0.33333334],
        [ 0.33333334,  0.33333334,  0.33333334],
        [ 0.33333334,  0.33333334,  0.33333334],
        [ 0.33333334,  0.33333334,  0.33333334],
        [ 0.33333334,  0.33333334,  0.33333334]], dtype=float32)]

In [59]:
btch_x,btch_y = ds.next_batch(10)
sess.run([logits,y],feed_dict={x:btch_x,y:btch_y})


[array([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]], dtype=float32), array([[ 1.,  0.,  0.],
        [ 1.,  0.,  0.],
        [ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.],
        [ 0.,  0.,  1.]], dtype=float32)]

In [63]:
btch_x,btch_y = ds.next_batch(10)
sess.run([tf.log(p)*y],feed_dict={x:btch_x,y:btch_y})

[array([[-1.09861231, -0.        , -0.        ],
        [-1.09861231, -0.        , -0.        ],
        [-0.        , -1.09861231, -0.        ],
        [-0.        , -0.        , -1.09861231],
        [-1.09861231, -0.        , -0.        ],
        [-0.        , -0.        , -1.09861231],
        [-0.        , -1.09861231, -0.        ],
        [-0.        , -1.09861231, -0.        ],
        [-0.        , -0.        , -1.09861231],
        [-0.        , -1.09861231, -0.        ]], dtype=float32)]

In [64]:
btch_x,btch_y = ds.next_batch(10)
sess.run([tf.reduce_sum(tf.log(p)*y,axis=1)],feed_dict={x:btch_x,y:btch_y})

[array([-1.09861231, -1.09861231, -1.09861231, -1.09861231, -1.09861231,
        -1.09861231, -1.09861231, -1.09861231, -1.09861231, -1.09861231], dtype=float32)]

In [65]:
optimizer = tf.train.GradientDescentOptimizer(.01)

In [66]:
loss = -tf.reduce_mean(tf.reduce_sum(tf.log(p)*y,axis=1))
train = optimizer.minimize(loss)

In [67]:
sess.run([W,b])

[array([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]], dtype=float32),
 array([[ 0.,  0.,  0.]], dtype=float32)]

In [68]:
for j in range(10):
    btch_x,btch_y = ds.next_batch(10)
    sess.run(train,feed_dict={x:btch_x,y:btch_y})

In [69]:
sess.run([W,b])

[array([[ -1.48515392e-05,  -1.27334089e-04,   1.42185614e-04],
        [  1.08354696e-04,  -1.12203503e-04,   3.84880332e-06],
        [ -2.57406937e-04,  -2.27286637e-05,   2.80135631e-04],
        [ -1.11687761e-04,  -1.29388045e-05,   1.24626560e-04]], dtype=float32),
 array([[ 0.00468672, -0.00632656,  0.00163984]], dtype=float32)]

In [92]:
for j in range(1000):
    btch_x,btch_y = ds.next_batch(10)
    sess.run(train,feed_dict={x:btch_x,y:btch_y})

In [83]:
sess.run([W,b])

[array([[-0.06877223,  0.00368724,  0.06508502],
        [ 0.0279085 , -0.02272538, -0.00518309],
        [-0.18771698,  0.03557696,  0.15213972],
        [-0.07778551,  0.00838733,  0.06939795]], dtype=float32),
 array([[ 0.05587947, -0.10309104,  0.04721267]], dtype=float32)]

In [73]:
tst_df = pd.read_csv('iris_test.csv',skiprows=1,header=None)
tst_ds = DataSet(tst_df.iloc[:,0:4].values,dense_to_one_hot(tst_df.iloc[:,4].values,num_classes=3),reshape=False)

In [74]:
tst_ds.next_batch(3)

(array([[ 0.02313726,  0.01176471,  0.01647059,  0.00588235],
        [ 0.02705882,  0.01215686,  0.02117647,  0.00823529],
        [ 0.02      ,  0.01294118,  0.00666667,  0.00196078]], dtype=float32),
 array([[ 0.,  1.,  0.],
        [ 0.,  0.,  1.],
        [ 1.,  0.,  0.]]))

In [75]:
# Check whether softmax gives a probability
btch_x,btch_y = tst_ds.next_batch(10)
sess.run([tf.reduce_sum(p,axis=1)],feed_dict={x:btch_x,y:btch_y})

[array([ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.00000012,  1.        ,  0.99999994], dtype=float32)]

In [84]:
btch_x,btch_y = tst_ds.next_batch(10)
sess.run([p,y],feed_dict={x:btch_x,y:btch_y})

[array([[ 0.34997565,  0.30004761,  0.34997678],
        [ 0.34998298,  0.30004197,  0.34997502],
        [ 0.34984311,  0.30005243,  0.35010445],
        [ 0.35072222,  0.29990792,  0.34936979],
        [ 0.35072953,  0.29990339,  0.34936705],
        [ 0.35012728,  0.30001497,  0.34985772],
        [ 0.35098234,  0.29988185,  0.34913573],
        [ 0.35083586,  0.29987291,  0.34929127],
        [ 0.34996641,  0.30003276,  0.35000077],
        [ 0.34983641,  0.30004802,  0.35011557]], dtype=float32),
 array([[ 0.,  1.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  1.,  0.],
        [ 1.,  0.,  0.],
        [ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 1.,  0.,  0.],
        [ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  1.,  0.]], dtype=float32)]

In [85]:
btch_x,btch_y = tst_ds.next_batch(10)
sess.run([tf.argmax(p,axis=1),tf.argmax(y,axis=1)],feed_dict={x:btch_x,y:btch_y})

[array([2, 2, 2, 0, 2, 0, 2, 2, 2, 2], dtype=int64),
 array([1, 1, 2, 1, 2, 0, 1, 2, 1, 1], dtype=int64)]

In [86]:
btch_x,btch_y = tst_ds.next_batch(10)
sess.run([tf.equal(tf.argmax(p,axis=1),tf.argmax(y,axis=1))],feed_dict={x:btch_x,y:btch_y})

[array([ True,  True,  True, False, False, False,  True,  True, False,  True], dtype=bool)]

In [88]:
accuracy = tf.reduce_mean(tf.cast(tf.equal(tf.argmax(p,axis=1),tf.argmax(y,axis=1)),tf.float32))

In [118]:
btch_x,btch_y = tst_ds.next_batch(11)
sess.run([accuracy],feed_dict={x:btch_x,y:btch_y})

[0.45454547]

In [119]:
dir(tst_ds)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_epochs_completed',
 '_images',
 '_index_in_epoch',
 '_labels',
 '_num_examples',
 'epochs_completed',
 'images',
 'labels',
 'next_batch',
 'num_examples']